name: sync_doc

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout jsbot
        uses: actions/checkout@v4
        with:
          path: jsbot
          fetch-depth: 0

      - name: Checkout jsbot_doc
        uses: actions/checkout@v4
        with:
          repository: ODYZZEIA-Discord-bot/jsbot_doc
          path: jsbot_doc
          token: ${{ secrets.GH_PAT }}

      - name: Sync doc directory
        run: |
          rm -rf jsbot_doc/doc
          cp -r jsbot/doc jsbot_doc/

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          cwd: jsbot_doc
          default_author: github_actions
          message: "[bot] Sync documentation"

